version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  veiculo-venda-api:
    build:
      context: ./veiculo-venda
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=veiculos_venda_db;Username=postgres;Password=postgres
    depends_on:
      - postgres
    ports:
      - "5001:80"
volumes:
  pgdata: