apiVersion: apps/v1
kind: Deployment
metadata:
  name: veiculo-venda
spec:
  replicas: 2
  selector:
    matchLabels:
      app: veiculo-venda
  template:
    metadata:
      labels:
        app: veiculo-venda
    spec:
      containers:
        - name: veiculo-venda
          image: veiculo.azurecr.io/veiculo-venda:latest
          ports:
            - containerPort: 8082
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          envFrom:
            - secretRef:
                name: veiculo-venda-secrets